[functions.send-contact-email]
verify_jwt = false

[functions.get-coach-program-url]
verify_jwt = false

[functions.delete-user-account]
verify_jwt = false

[functions.dispatch-coach-weekly-feedbacks]
verify_jwt = false
